### Numpy é uma biblioteca de álgebra linear para python que é o bloco de construção de todas as outras bibliotecas de análise de dados. É uma biblioteca expremamente rápida.

In [113]:
#importando o numpy
import numpy as np

In [114]:
#array unidimensional 
array1 = np.array([1,2,3,4])

In [115]:
#array bi-dimensional
array2 = np.array([[3,2,1],[1,2,3]])

In [116]:
array1


array([1, 2, 3, 4])

In [117]:
array2

array([[3, 2, 1],
       [1, 2, 3]])

In [118]:
#formato do array
array1.shape

(4,)

In [119]:
array2.shape

(2, 3)

In [120]:
#numero de dimensoes
array1.ndim


1

In [121]:
array2.ndim

2

In [130]:
array1.max()

4

Observe que ndim e shape são atributos, já o max() é um método

In [131]:
#retorna qual o indice do maior elemendo do vetor(no caso o  primeiro maior que aparece, caso tenha repetição)
array1.argmax()

3

In [132]:
array1.min()

1

In [134]:
array1.argmin()

0

## Estruturas de dados com arange

In [30]:
#cria um vetor de 0 a 10
array3 = np.arange(10)

In [31]:
array3

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [32]:
#cria um vetor com (comeco,fim,passo), onde passo é o quanto "pula" do inicio ate o fim (o fim nao entra)
array4 = np.arange(0,20,5)

In [33]:
array4

array([ 0,  5, 10, 15])

## Usando o linspace

In [34]:
#argumentos(inicio, fim, numero de elementos) 
#o inicio e fim no linspace entra
array5 = np.linspace(0,20,3) 

In [35]:
array5

array([ 0., 10., 20.])

## Usando outras funções

### numpy.zeros

In [53]:
# array só com zeros
array6 = np.zeros((5,9))

In [54]:
vetor5

array([[0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0.]])

### numpy.ones

In [55]:
# array só de uns - matriz tridimensional
array7 = np.ones((2,3,1))

In [56]:
array7

array([[[1.],
        [1.],
        [1.]],

       [[1.],
        [1.],
        [1.]]])

### numpy.eye

In [49]:
#matriz identidade
array8 = np.eye(4)

In [50]:
array8

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

### numpy.diag

In [64]:
#matriz diagonal
array9 = np.diag((1,4,9,25,36)); array9

array([[ 1,  0,  0,  0,  0],
       [ 0,  4,  0,  0,  0],
       [ 0,  0,  9,  0,  0],
       [ 0,  0,  0, 25,  0],
       [ 0,  0,  0,  0, 36]])

### numpy.random.rand e numpy.random.randn

In [69]:
#a função rand(n) gera uma sequência de números distribuidos uniformemente de 0 a n
np.random.seed(100)
array10 = np.random.rand(5); array10

array([0.54340494, 0.27836939, 0.42451759, 0.84477613, 0.00471886])

In [70]:
#a função randn(n) produz uma sequência de números com distribuição normal (Gaussiana) 
array11 = np.random.randn(5); array11

array([ 0.35467445, -0.78606433, -0.2318722 ,  0.20797568,  0.93580797])

### numpy.empty

In [74]:
array12 = np.empty((3,2)); array12

array([[1., 1.],
       [1., 1.],
       [1., 1.]])

### numpy.tile

In [75]:
np.array([[9,4],[3,7]])

array([[9, 4],
       [3, 7]])

In [76]:
np.tile((np.array([[9,4],[3,7]])),4)

array([[9, 4, 9, 4, 9, 4, 9, 4],
       [3, 7, 3, 7, 3, 7, 3, 7]])

In [77]:
np.tile(np.array([[9,4],[3,7]]), (2,2))

array([[9, 4, 9, 4],
       [3, 7, 3, 7],
       [9, 4, 9, 4],
       [3, 7, 3, 7]])

## Tipos de dados numpy

In [78]:
array13 = np.array([[8,-3,5,9]], dtype = 'float')

In [79]:
array13

array([[ 8., -3.,  5.,  9.]])

In [80]:
array13.dtype

dtype('float64')

In [81]:
array14 = np.array([2,4,6,8])

In [82]:
array14.dtype

dtype('int64')

In [83]:
array15 = np.array([2.0,4,5,0])

In [84]:
array15.dtype

dtype('float64')

In [85]:
array16 = np.array(['analise', 'de', 'dados', 'com', 'python'])

In [86]:
array16.dtype

dtype('<U7')

In [87]:
array17 = np.array([True,False])

In [88]:
array17.dtype

dtype('bool')

In [89]:
array18 = np.array([7, -3, 5.24])

In [90]:
array18.dtype

dtype('float64')

In [92]:
array18.astype(int)

array([ 7, -3,  5])

## Operações com arrays

In [93]:
array19 = np.arange(0,30) * 5

In [94]:
array19

array([  0,   5,  10,  15,  20,  25,  30,  35,  40,  45,  50,  55,  60,
        65,  70,  75,  80,  85,  90,  95, 100, 105, 110, 115, 120, 125,
       130, 135, 140, 145])

In [95]:
array20 = np.arange(5) ** 4

In [96]:
array20

array([  0,   1,  16,  81, 256])

In [97]:
array21 = np.arange(30) + 1

In [98]:
array21

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30])

In [99]:
array22 = np.arange(0,30,3) + 3
array23 = np.arange(1,11)

In [100]:
array22

array([ 3,  6,  9, 12, 15, 18, 21, 24, 27, 30])

In [101]:
array23

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [102]:
#subtracao
array22 - array23

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [103]:
#adicao
array22 + array23

array([ 4,  8, 12, 16, 20, 24, 28, 32, 36, 40])

In [104]:
#divisao
array22/array23

array([3., 3., 3., 3., 3., 3., 3., 3., 3., 3.])

In [105]:
#multiplicação
array22 * array23

array([  3,  12,  27,  48,  75, 108, 147, 192, 243, 300])

In [106]:
#comparação
array22 > array23

array([ True,  True,  True,  True,  True,  True,  True,  True,  True,
        True])

In [107]:
array24 = np.array([True, False, True, False])
array25 = np.array([False, False, True, False])

In [108]:
np.logical_and(array24,array25)

array([False, False,  True, False])

## Numpy é mais rápido do que criar diretamente no python

In [110]:
array_numpy = np.arange(1000)
%timeit array_numpy ** 4

6.1 µs ± 365 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)


In [111]:
array_python = range(1000)
%timeit [array_python[i] ** 4 for i in array_python]

423 µs ± 51.6 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)
