In [1]:
import numpy as np

In [2]:
array1 = np.arange(5); array1

array([0, 1, 2, 3, 4])

In [3]:
#primeiro elemento do array ( a indexação em python começa no 0)
array1[0]

0

In [4]:
#ultimo elemento do array
array1[-1]

4

In [5]:
#invertendo o array
array1[::-1]

array([4, 3, 2, 1, 0])

## Array multidimensional

In [8]:
array2 = np.array([[190,290,490],[129,458,567],[761,902,346]])

In [9]:
array2

array([[190, 290, 490],
       [129, 458, 567],
       [761, 902, 346]])

In [10]:
#slicing da matriz
array2[2,1]

902

In [12]:
#atrubuindo um valor a um elemento da matriz
array2[1,1] = 10

In [13]:
array2

array([[190, 290, 490],
       [129,  10, 567],
       [761, 902, 346]])

In [15]:
array2[2]

array([761, 902, 346])

In [16]:
array2[2,]

array([761, 902, 346])

In [18]:
array2[:,1]

array([290,  10, 902])

## Slicing de array

In [19]:
array3 = np.arange(50) * 2; array3

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32,
       34, 36, 38, 40, 42, 44, 46, 48, 50, 52, 54, 56, 58, 60, 62, 64, 66,
       68, 70, 72, 74, 76, 78, 80, 82, 84, 86, 88, 90, 92, 94, 96, 98])

In [20]:
array3[5:10:2]

array([10, 14, 18])

In [21]:
#retorna todos os valores até o elemento de index 4 (exclusive)
array3[:4]

array([0, 2, 4, 6])

In [24]:
#retorna todos os valores a partir do index 4 (inclusive)
array3[4:]

array([ 8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40,
       42, 44, 46, 48, 50, 52, 54, 56, 58, 60, 62, 64, 66, 68, 70, 72, 74,
       76, 78, 80, 82, 84, 86, 88, 90, 92, 94, 96, 98])

In [25]:
#o slicing não altera o objeto inicial
array3

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32,
       34, 36, 38, 40, 42, 44, 46, 48, 50, 52, 54, 56, 58, 60, 62, 64, 66,
       68, 70, 72, 74, 76, 78, 80, 82, 84, 86, 88, 90, 92, 94, 96, 98])

In [26]:
#mas podemos usar o slicing para alterar elementos ou conjutos de elementos dentro do array
array3[:4] = 1

In [27]:
array3


array([ 1,  1,  1,  1,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32,
       34, 36, 38, 40, 42, 44, 46, 48, 50, 52, 54, 56, 58, 60, 62, 64, 66,
       68, 70, 72, 74, 76, 78, 80, 82, 84, 86, 88, 90, 92, 94, 96, 98])

In [31]:
#atribuindo um array a partir de outro array
array3[:8] = np.ones(8); array3

array([ 1,  1,  1,  1,  1,  1,  1,  1, 16, 18, 20, 22, 24, 26, 28, 30, 32,
       34, 36, 38, 40, 42, 44, 46, 48, 50, 52, 54, 56, 58, 60, 62, 64, 66,
       68, 70, 72, 74, 76, 78, 80, 82, 84, 86, 88, 90, 92, 94, 96, 98])

## criando um subset de um array e copiando com np.copy

In [33]:
array4 = np.arange(12); array4

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [34]:
array5 = array4[::2]

In [35]:
array5

array([ 0,  2,  4,  6,  8, 10])

In [36]:
array6 = np.copy(array5)

In [ ]:
#Usar o numpy.copy é interessante porque quando criamos um vetor arr1 = arr2, se eu mudar o arr1 eu
#acabo mudando o arr2, uma vez que eles apontam pro mesmo endereço de memória. Usando o copy driblamos 
#esse problema. Vejamos um exemplo:

In [37]:
array6

array([ 0,  2,  4,  6,  8, 10])

In [39]:
array7 = array6[2:]; array7

array([ 4,  6,  8, 10])

In [41]:
array7[:] = 100; array7

array([100, 100, 100, 100])

In [42]:
array6

array([  0,   2, 100, 100, 100, 100])